---
title: "iteration_notes"
output: github_document
date: "2023-10-31"
---

```{r}
library(tidyverse)
library(rvest)
```

```{r}
set.seed(12345)
```


## lists 

```{r}
vec_numeric = 1:4
vec_char = c("My", "name", "is", "Jeff")

tibble(
  num = vec_numeric,
  char = vec_char)
```

different stuff with different lengths

```{r}
l = 
  list(
vec_numeric = 1:5,
vec_char = LETTERS,
matrix = matrix(1:10, nrow = 5, ncol = 2),
summary = summary(rnorm(100))
)
```

accessing lists 

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```
## loops 

```{r}
list_norm_Samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0 ,7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )

mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, 
       sd = sd_x)
}
```

```{r}
mean_and_sd(list_norm_Samples$a)
mean_and_sd(list_norm_Samples$b)
mean_and_sd(list_norm_Samples$c)
mean_and_sd(list_norm_Samples$d)
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norm_Samples[[i]])
}
```

## use `map`

```{r}
output = map(list_norm_Samples, mean_and_sd)

output_med = map(list_norm_Samples, median)

output_sum = map(list_norm_Samples, summary)
```

## create df

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm_Samples
  )
```

```{r}
listcol_df %>% 
  pull(samp)

mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])
mean_and_sd(listcol_df$samp[[3]])

map(listcol_df$samp, mean_and_sd)

listcol_df %>% 
  mutate(
    mean_sd = map(samp, mean_and_sd),
    median = map(samp, median)) %>% 
  pull(mean_sd)

listcol_df %>% 
  mutate(
    mean_sd = map(samp, mean_and_sd),
    median = map(samp, median)) %>% 
  select(name, mean_sd) %>% 
  unnest(mean_sd)
```
# issue here, should have separated mean and sd

### NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

nsduh_import <- function(html, table_num, outcome_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      name = outcome_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}

nsduh_import(nsduh_html, 1, "marj")
nsduh_import(nsduh_html, 4, "cocaine")
nsduh_import(nsduh_html, 5, "heroin")
```

import data using for a loop

```{r}
table_input = list(1, 4, 5)
name_input = list("marj", "cocaine", "heroin")

output = vector("list", length = 3)

for(i in c(1:3)) {
  output[[i]] = nsduh_import(nsduh_html, table_input[[i]], name_input[[i]])
}

nsduh_df = bind_rows(output)
```

try again using maps 

```{r}
nsduh_import <- function(html, table_num) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}


nsduh_df = 
  tibble(
    name = c("marj", "cocaine", "heroin"), 
    number = c(1, 4, 5)
  ) %>% 
  mutate(table = map(number, nsduh_import, html = nsduh_html))

map(nsduh_df$number, nsduh_import, html = nsduh_html)
```
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

```{r}
weather_nest_df =
  weather_df%>% 
  nest(df = date:tmin)
```

can i regress `tmax` on `tmin` for each of these?

```{r}
central_park_df = 
  weather_nest_df %>% 
  pull(df) %>% 
  nth(1)
```

```{r}
lm(tmax ~ tmin, data = central_park_df)
```

fit a linear regression for central park 

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}
```

```{r}
input_list = weather_nest_df %>% pull(df)
output = vector("list", length = 3)

for (i in 1:3) {
  output[[i]] = weather_lm(input_list[[i]])
}
```



